# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YKDouyin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'MJRefresh'

  # Pods for YKDouyin

  target 'YKDouyinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YKDouyinUITests' do
    # Pods for testing
  end

end
